---
- name:
  hosts: localhost
  vars:
    pkg: httpd
    srv: httpd
  tasks:
    - name:
      yum:
        name: "{{pkg}}"
        state: latest
    - name:
      service:
        name: "{{srv}}"
        enabled: true
        state: started
